### PR TITLE
bump firefox maxVersion to 40

### PR DESCRIPTION
**Pull request by plroman**
Hi,
firefox 40 is now available so the maxVersion needs a bump. It will probably need a bigger bump soon.
I didn't test it and I don't if some other metadatas (e.g., id) need to be changed too.

### CODE REVIEW

**Comment by dffischer** [comment]
The current version is 41 since a few days, so I suggest changing the maxVersion to 41 directly. As far as I can tell, the Add-On works flawlessly with this version.

**Comment by plroman** [comment]
Branch updated: bump to maxVersion 50 for both firefox and thunderbird.

I made this bump a few weeks ago and it worked well for me. I think the max version was arbitrarily set, so 50 is probably fine for now, or maybe even too small.

**Comment by swick** [comment]
Supported versions are only increased after actually testing if they are supported.

**Comment by dffischer** [comment]
Thank you for the update. Can we do anything to help testing with future Firefox versions?

**Comment by swick** [comment]
Yes, sure, just test adding, removing and using passwords and report if anything doesn't work. I'll try to bumb the supported versions whenever I do a release.

**Comment by dffischer** [comment]
As I maintain [a package of this extension for Arch Linux](https://aur.archlinux.org/packages/mozilla-extension-gnome-keyring-git/), that is usually what I do anyway when a new stable Firefox version hits the distribution's repositories. If the version in question is not yet noted here, I will then inform you via a pull request.

**Pull request closed without merging**
